spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor_test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '#Depu2453'

  # JPA Settings
  jpa.hibernate.ddl_auto: update